
name: Astro Build

on: [push, pull_request]

jobs:

  update-info:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository first.
        uses: actions/checkout@v4
    
      - name: Write commit ID.
        run: |
          shortSHA=$( git rev-parse --short ${{ github.sha }} )
          sed -i "1i local id = \"$shortSHA\"" build/info.lua

      - name: Install Lua.
        run: |
          sudo apt update
          sudo apt install -y lua5.4

      - name: Run Lua script to update information.
        run: lua build/info.lua

      - name: Push.
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Astro information updated."
          git push
